/**
 * Where every pin physically sits.
 *
 * Geometry is kept out of the React components so that hit-testing, wire
 * routing, breadboard hole contact and rendering all agree on one set of
 * coordinates. All values are in workspace units (1 unit = 1 px at zoom 1).
 */
import type { ComponentModel, PlacedComponent } from './types';

export const GRID = 10;
/** 0.1 inch pin pitch, and the breadboard hole pitch. */
export const PIN_PITCH = 20;

const DIP_BODY_W = 100;
const DIP_LEG = 15;
export const DIP_W = DIP_BODY_W + DIP_LEG * 2; // 130
const DIP_PAD = 15;

export interface PinPos {
  n: number;
  x: number;
  y: number;
  side: 'L' | 'R' | 'T' | 'B';
}

export interface Layout {
  w: number;
  h: number;
  pins: PinPos[];
  /** The drawn body, inset from the bounding box by the pin legs. */
  bodyX: number;
  bodyY: number;
  bodyW: number;
  bodyH: number;
}

function dipLayout(pinCount: number): Layout {
  const perSide = pinCount / 2;
  const h = 2 * (DIP_PAD + 10) + (perSide - 1) * PIN_PITCH;
  const pins: PinPos[] = [];
  for (let i = 1; i <= perSide; i++) {
    pins.push({ n: i, x: 0, y: DIP_PAD + 10 + (i - 1) * PIN_PITCH, side: 'L' });
  }
  for (let i = 1; i <= perSide; i++) {
    pins.push({
      n: perSide + i,
      x: DIP_W,
      y: DIP_PAD + 10 + (perSide - i) * PIN_PITCH,
      side: 'R',
    });
  }
  return {
    w: DIP_W,
    h,
    pins,
    bodyX: DIP_LEG,
    bodyY: 0,
    bodyW: DIP_BODY_W,
    bodyH: h,
  };
}

type ModuleSpec = { w: number; h: number; pins: PinPos[] };

/**
 * Module pins sit on the same 0.1 inch pitch as the breadboard holes, and every
 * pin of a part is a whole number of pitches from its first pin. That is what
 * lets any part - not just a DIP - drop into the board with every leg seated.
 */
function stack(count: number, x: number, side: 'L' | 'R', top: number, pitch = PIN_PITCH): PinPos[] {
  return Array.from({ length: count }, (_, i) => ({ n: i + 1, x, y: top + i * pitch, side }));
}

const IO_TOP = 40;
const IO_H = IO_TOP + 7 * PIN_PITCH + 32;

const MODULE_LAYOUTS: Record<string, () => ModuleSpec> = {
  writer: () => ({ w: 200, h: IO_H, pins: stack(8, 200, 'R', IO_TOP) }),
  reader: () => ({ w: 200, h: IO_H, pins: stack(8, 0, 'L', IO_TOP) }),
  vcc: () => ({ w: 80, h: 44, pins: [{ n: 1, x: 40, y: 44, side: 'B' }] }),
  gnd: () => ({ w: 80, h: 44, pins: [{ n: 1, x: 40, y: 0, side: 'T' }] }),
  led: () => ({
    w: 60,
    h: 60,
    pins: [
      { n: 1, x: 20, y: 60, side: 'B' },
      { n: 2, x: 40, y: 60, side: 'B' },
    ],
  }),
  switch: () => ({
    w: 80,
    h: 64,
    pins: [
      { n: 1, x: 20, y: 64, side: 'B' },
      { n: 2, x: 40, y: 64, side: 'B' },
      { n: 3, x: 60, y: 64, side: 'B' },
    ],
  }),
  pushbutton: () => ({
    w: 80,
    h: 64,
    pins: [
      { n: 1, x: 20, y: 64, side: 'B' },
      { n: 2, x: 40, y: 64, side: 'B' },
      { n: 3, x: 60, y: 64, side: 'B' },
    ],
  }),
  clock: () => ({ w: 120, h: 72, pins: [{ n: 1, x: 120, y: 36, side: 'R' }] }),
  seg7: () => ({
    w: 120,
    h: 130,
    pins: [
      ...stack(5, 0, 'L', 20),
      { n: 6, x: 120, y: 20, side: 'R' },
      { n: 7, x: 120, y: 40, side: 'R' },
      { n: 8, x: 120, y: 60, side: 'R' },
      { n: 9, x: 120, y: 80, side: 'R' },
    ],
  }),
  resistor: () => ({
    w: 80,
    h: 32,
    pins: [
      { n: 1, x: 0, y: 16, side: 'L' },
      { n: 2, x: 80, y: 16, side: 'R' },
    ],
  }),
  pullup: () => ({ w: 60, h: 56, pins: [{ n: 1, x: 30, y: 56, side: 'B' }] }),
  pulldown: () => ({ w: 60, h: 56, pins: [{ n: 1, x: 30, y: 0, side: 'T' }] }),
  probe: () => ({ w: 72, h: 40, pins: [{ n: 1, x: 0, y: 20, side: 'L' }] }),
};

/**
 * True when every pin of a part is a whole number of hole pitches away from its
 * first pin, i.e. the part can be seated in the board with all legs in holes.
 */
export function seatsOnBoard(model: ComponentModel): boolean {
  const l = layoutOf(model);
  if (!l.pins.length) return false;
  const [first, ...rest] = l.pins;
  return rest.every(
    (p) => (p.x - first.x) % PIN_PITCH === 0 && (p.y - first.y) % PIN_PITCH === 0,
  );
}

/** Breadboard geometry is generated by `breadboard.ts` and cached here. */
export const boardLayouts = new Map<string, Layout>();

export function layoutOf(model: ComponentModel, comp?: PlacedComponent): Layout {
  if (model.pkg === 'DIP14') return dipLayout(14);
  if (model.pkg === 'DIP16') return dipLayout(16);

  if (model.category === 'board') {
    const key = `${model.type}:${comp?.props?.cols ?? 'default'}`;
    const cached = boardLayouts.get(key);
    if (cached) return cached;
  }

  const spec = MODULE_LAYOUTS[model.type]?.() ?? {
    w: 100,
    h: 60,
    pins: model.pins.map((p, i) => ({ n: p.n, x: 0, y: 20 + i * 20, side: 'L' as const })),
  };
  return { ...spec, bodyX: 0, bodyY: 0, bodyW: spec.w, bodyH: spec.h };
}

/** Bounding box of a component after rotation. */
export function boundsOf(model: ComponentModel, comp: PlacedComponent) {
  const l = layoutOf(model, comp);
  const swapped = comp.rot === 90 || comp.rot === 270;
  return {
    x: comp.x,
    y: comp.y,
    w: swapped ? l.h : l.w,
    h: swapped ? l.w : l.h,
  };
}

/** Map a point in the component's own frame into workspace coordinates. */
export function toWorld(
  comp: PlacedComponent,
  l: Layout,
  x: number,
  y: number,
): { x: number; y: number } {
  switch (comp.rot) {
    case 90:
      return { x: comp.x + l.h - y, y: comp.y + x };
    case 180:
      return { x: comp.x + l.w - x, y: comp.y + l.h - y };
    case 270:
      return { x: comp.x + y, y: comp.y + l.w - x };
    default:
      return { x: comp.x + x, y: comp.y + y };
  }
}

/** The SVG transform that puts a component's own frame at the right place. */
export function transformOf(comp: PlacedComponent, l: Layout): string {
  const t =
    comp.rot === 90
      ? { x: l.h, y: 0 }
      : comp.rot === 180
        ? { x: l.w, y: l.h }
        : comp.rot === 270
          ? { x: 0, y: l.w }
          : { x: 0, y: 0 };
  return `translate(${comp.x + t.x} ${comp.y + t.y}) rotate(${comp.rot})`;
}

/** Which way a wire should leave a pin, after rotation. */
export function worldSide(side: PinPos['side'], rot: number): PinPos['side'] {
  const order: PinPos['side'][] = ['T', 'R', 'B', 'L'];
  const i = order.indexOf(side);
  return order[(i + rot / 90) % 4];
}

export function pinWorldPos(
  model: ComponentModel,
  comp: PlacedComponent,
  pin: number,
): { x: number; y: number; side: PinPos['side'] } | null {
  const l = layoutOf(model, comp);
  const p = l.pins.find((q) => q.n === pin);
  if (!p) return null;
  const w = toWorld(comp, l, p.x, p.y);
  return { ...w, side: worldSide(p.side, comp.rot) };
}

export const snapTo = (v: number, step = GRID) => Math.round(v / step) * step;
